### ISSUE TITLE
 MMM-Strava only shows achievements, nothing else? 

### ISSUE THREAD

**Issue by nakulbende** [ianperrin/MMM-Strava#44] opened 2020-06-25 13:47 UTC
Hey all,

I installed MMM-Strava, followed the wonderfully documented instructions on how to get authentication tokens - but am having some issues. I think my authentication is fine, because the module shows my weekly achievements. But, it does not show ride #, distances or any other stats. Here is my config file and screenshot:

![image](https://user-images.githubusercontent.com/8712050/85731789-cf8c1500-b6c8-11ea-9801-74460c84ed09.png)

```
{
	module: "MMM-Strava",
	position: "bottom_left",
	config: {
		client_id: "XXXX",
		client_secret: "XXXXXXX",
		mode: "table",
		activities: "ride",
		reloadInterval: 1000*60*30,
		stats: ["count", "distance", "elevation", "moving_time", "achievements"]
	}
}
```

Here is the relevant output from `npm start`

```
> magicmirror@2.11.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[2020-06-25 09:31:12.157] [LOG]    Starting MagicMirror: v2.11.0
[2020-06-25 09:31:12.191] [LOG]    Loading config ...
[2020-06-25 09:31:12.210] [LOG]    Loading module helpers ...

[2020-06-25 09:31:20.444] [LOG]    Initializing new module helper ...
[2020-06-25 09:31:20.446] [LOG]    Check MagicMirror version for node helper 'MMM-Strava' - Minimum version:  2.2.0 - Current version: 2.11.0
[2020-06-25 09:31:20.448] [LOG]    Version is ok!
[2020-06-25 09:31:20.450] [LOG]    Module helper loaded: MMM-Strava

[2020-06-25 09:31:22.042] [LOG]    Connecting socket for: MMM-Strava
[2020-06-25 09:31:22.044] [LOG]    Starting module helper: MMM-Strava
```

**Comment by ianperrin** [comment] 2020-07-21 21:32
@nakulbende - if you are having this issue, could you check if all your activities are marked as private?

**Comment by jamiemcg10** [comment] 2020-12-17 20:16
Have you tried changing the activities value in the config.js file from "ride" to  ["ride"]? The value(s) should be in an array.

**Comment by ianperrin** [comment] 2021-03-27 10:09
@nakulbende are you still experiencing this issue, if so, please look at the config options and whether you are using private activities.

**Comment by ianperrin** [comment] 2021-04-06 23:09
I was unable to reproduce this error and as it has been some time since it was reported I am going to close the issue.

If you are still experiencing the error, please do re-open the issue. Thanks

**Closed by ianperrin** 2021-04-06 23:10 UTC
Labels: question
