### ISSUE TITLE
Stats stopped updating if mode: "chart"

### ISSUE THREAD

**Issue by ebonak** [ianperrin/MMM-Strava#60] opened 2021-08-12 21:31 UTC
Platform (Hardware/OS): Raspberry Pi 3 with Raspian v 10 (buster)

Node Version: 6.14.13

MagicMirror Version: 2.16.0

Description: I installed this at the start of June. I specified mode: "chart" to also be able to track walks in addition to runs and everything worked great. However, in the last few weeks my stats didn't update. I finally tracked this to the mode parameter/setting. When I comment this out, or specify the default of "table" the stats get updated, but I don't get my walk mileage. In both cases the API calls get made (looking at the Strava dashboard) and I'm assuming the information is retrieved. It just doesn't get updated/displayed correctly if mode is set to "chart".

I believe that last update that worked with "chart" was July 19.

As part of my troubleshooting I updated everything and at some point reinstalled the module fresh before I was able to determine the mode setting to be the determining factor.

Configuration:

	    config: {
		client_id: "xxx",
		client_secret: "yyy",
		mode: "table",
		activities: ["run", "walk"],
		stats: ["distance", "count"],
		period: "ytd",
		debug: true
	    }

Additional Notes: 

I posted about this here too 

https://forum.magicmirror.builders/topic/15366/mmm-strava-stopped-updating/17?page=2

With mode: "chart" - incorrect miles and count

![image](https://user-images.githubusercontent.com/4589843/129272069-8efbbf58-56e0-40c2-9f16-343cf2af4d32.png)

with mode: "table" - correct miles/count
![image](https://user-images.githubusercontent.com/4589843/129272126-7af142e1-5b56-4473-b69e-98a40bb61b62.png)

**Comment by ianperrin** [comment] 2021-09-10 08:24
Hi @ebonak - this looks like a duplicate of #46 where only the first 200 activities returned from the strata api are evaluated and summarised in the chart. I've a fix in progress, but in the meantime, try changing the config so that `period: "recent"` as a workaround

**Comment by ianperrin** [comment] 2021-09-10 08:25
Closing this issue as a duplicate - please track #46 for updates.

**Closed by ianperrin** 2021-09-10 08:25 UTC
Labels: duplicate

**Comment by ebonak** [comment] 2021-09-10 22:23
The suggested workaround  is not working for me unfortunately.


![image](https://user-images.githubusercontent.com/4589843/132923266-01a1f2d0-9f6c-4189-87d7-d328ee1a8c78.png)


Here's the modified config file

````
//		mode: "table",
		mode: "chart",		
		activities: ["run", "walk"],
		stats: ["distance", "count"],
//		period: "ytd",
		period: "recent",		
//		reloadInterval: "300000", // every 5 minutes
		debug: true
	    }
	},
````

This is what the numbers should be:

![image](https://user-images.githubusercontent.com/4589843/132923606-41533980-337c-4263-81fb-e25fa0cdff67.png)

I will look at the other issue mentioned to see if I missed anything in the modification instruction. As of now it looks like I will have to wait for an update?

Thanks.

**Comment by ianperrin** [comment] 2021-09-11 14:48
Hi @ebonak 

When using `period: 'recent'` only the activities from the current week are shown in the chart and stats. Is is possible the module is correct on this basis?

FYI - I published some updates for the module yesterday which include a fix for the 200 activity limit. Are you able to update the module and re-install the dependencies as described in the readme - https://github.com/ianperrin/MMM-Strava#updating-the-module ? Once you've done that, you should be able to revert to using `period: 'ytd'`

Let me know if this works for you.

Thanks

**Comment by ebonak** [comment] 2021-09-11 14:51
Hi,

I updated it via the remote control module yesterday , but I will do this again manually later today and report back. I had done the manual re-install earlier while trying to determine the problem.

I appreciate your help, I'll let you know if another update will fix the problem

**Comment by ebonak** [comment] 2021-09-11 16:12
> Hi @ebonak
> 
> When using `period: 'recent'` only the activities from the current week are shown in the chart and stats. Is is possible the module is correct on this basis?
> 

Ah .. sorry, missed that part, yes, the stats are correct for the past week, so I won't try to manually update this again.  For now I'll revert to the table format and ytd (though I won't get the walking stats) to see my running stats for the year so far. I'll keep an eye out for a future update.

Thanks again.
